### ISSUE TITLE
Updating in general

### ISSUE THREAD

**Issue by ZeeD26** [cayennes/kanji-colorize#39]
Thank you for this nice little tool that helps me learn all the Kanji!

While browsing the code it seemed to me like everything got a little dusty over the year, e.g., Python3 does not seem to be supported. Is there any interest from your side to _polish_ this repository a bit? I would be happy to help and just fire some pull requests.

**Comment by cayennes** [comment]
Hi

I'm glad it's been useful for you!

It has indeed gotten a bit dusty, and I would be more than happy to accept pull requests to fix it up, just ask me ahead of time for anything large scale you want to do to make sure we agree on whether it's valuable and the approach.

Updating it to python3 would be great.  Do you use the anki addon or use the diagrams another way?  Anki compatibility is the top priority.  It looks like there's an alpha version of anki that uses python3 (maybe that's why you sent this.)

**Comment by cayennes** [comment]
Closing this since it is not a specific actionable thing.
Also the python3 update did happen.
