### ISSUE TITLE
Direct SVG inside the Diagram Field

### ISSUE THREAD

**Issue by thatfatblackcat** [cayennes/kanji-colorize#67]
I'd be really nice if you added support for direct SVG inside the diagram field, just like Yomichan does when you import a pitch accent graph. I don't like having many files lying around my media folder.

That shouldn't be too hard to implement, unfortunately I don't know python and I can't add that feature myself. Also, you could have a new setting that you can toggle on and off, based on your preferences.

**Comment by cayennes** [comment]
> I don't like having many files lying around my media folder.

So I know how to prioritize this, can you let me know what problems
specifically this causes?

> That shouldn't be too hard to implement

I know it’s not what you were intending to communicate, but pointing out
that you see the time I spend on this as trivial is not the way to make
me feel like helping you. You’re probably right that it’s not
technically difficult. Getting anything at all done after everything
else in life is hard. Personally I’m not doing this because I don’t have
enough to do. If you don’t have enough to do, I highly recommend
learning to program. It takes time but not as much as you might think,
and it’s useful for a lot of things.

If you convince me that this has practical value, I’ll do it at a time
that seems appropriate to me. 

On March 24, 2021, GitHub notifications ***@***.***>
wrote:
> I'd be really nice if you added support for direct SVG inside the
> diagram field, just like Yomichan does when you import a pitch accent
> graph. I don't like having many files lying around my media folder.
>
> That shouldn't be too hard to implement, unfortunately I don't know
> python and I can't add that feature myself. Also, you could have a new
> setting that you can toggle on and off, based on your preferences.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cayennes/kanji-colorize/issues/67>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAL23KB2QYAVYNIDD7YVRRLTFHA7XANCNFSM4ZXARNWQ>.

**Comment by thatfatblackcat** [comment]
> pointing out that you see the time I spend on this as trivial [...]
I haven't, in fact it's quite the opposite of what you interpreted. I really like your project, I think it adds value to Anki's default experience, and that's also the reason I decided to come here and comment.

About the media folder, I was referring to `~/.local/share/Anki2/profile-01/collection.media/` where generated SVG images are stored (idk on Windows where its could be located, but I suspect under `%Appdata%`). The more cards you have the more this folder gets bigger and bigger.

That might not be a problem to anyone, but I think if we could reduce the amount of files that get into that folder the more manageable cards would be. As I said, that's just my personal opinion, I am not forcing you make a change if you don't see any advancements: It was just a suggestion.

> I highly recommend learning to program.
I already know how to program, I just said that I don't know python. I personally enjoy more posix shell and web dev.

**Comment by cayennes** [comment]
Thanks for taking the time to explain all of that.

I'm going to close this for now. Regardless of the time it takes, I'm not sure it would be an improvement - keeping the SVGs as card content instead of media could interfere with anki's ability to optimize syncing.

But if this creates problems for anyone, let me know and I will consider reopening it.
